baseURL = "https://blog.juanwolf.fr"
languageCode = "en"
defaultContentLanguage = "en"
title = "blog.juanwolf.fr - Jean-Loup's Adde blog about software engineering and video games"

PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

hasCJKLanguage = false
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

paginate = 10
copyright = ""

googleAnalytics = "UA-116906295-2"

[author]
    name = "Jean-Loup Adde"

[sitemap]
    changefreq = "weekly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    author = "Jean-Loup Adde"
    description = "Personal blog about software engineering and video games"
    githubUsername = "#juanwolf"
    accent = "#009688"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    since = "2014"
    rssFullContent = true

    logoTitle = "blog.juanwolf.fr"
    keywords = [""]
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python", "bash", "shell", "javascript", "scala"]

    moreMeta = true


[params.reward]
    enable = false

[params.social]
    a-email = "mailto:"
    c-twitter = "https://twitter.com/juan__wolf"
    g-github = "https://github.com/juanwolf"
    n-gitlab = "http://gitlab.com/juanwolf"

[[menu.main]]
    url = "/post/programming/"
    name = "Programming"
    weight = 1

[[menu.main]]
    url = "/post/video-games/"
    name = "Video Games"
    weight = 2

[[menu.main]]
    url = "/post/others/"
    name = "Others"
    weight = 3

[[menu.main]]
  name = "Tags"
  weight = 4
  identifier = "tags"
  url = "/tags/"

[languages]
[languages.en]
    title = "blog.juanwolf.fr - Jean-Loup Adde's blog"
    weight = 1
    languageCode = "en"

[languages.fr]
    title = "blog.juanwolf.fr - Le blog de Jean-Loup Adde"
    weight = 2
    languageCode = "fr"
