#+title: About
#+date: 2017-08-20

** Welcome dear Web:surfer:!

I'm Jean-Loup Adde (nice to meet you :smile:), a 25 year old software developer. I have a crush on all the technologies around the web, automation, and maybe too many others. I used to host all my stuff on specific VMs writting custom code. And recently I decided, screw that, why bothering with so many layers when you just want to write some posts in Markdown! So bye bye DBs, bye bye Web Frameworks, hello fully static generated website hosted on [[https://netlify.com][netlify.com]].

In case you're wondering what tech I use for this blog, everything's made with [[https://gohugo.io/][hugo]] using the [[https://en.xianmin.org/hugo-theme-jane/][jane theme]] that I changed a bit ([[https://github.com/juanwolf/hugo-theme-jane/tree/master][modifications here]]).

** History

You're currently at the v2 of my blog. At the beginning it was a django application that I wrote from scratch. To be honest it was an awesome challenge for me at the time (2014, student of master 1 in Software Engineering). I wrote everything from scratch, CSS, HTML, python. It was hard to say goodbye to the old version, it was like saying goodbye to an old friend or a younger version of myself. Weird, isn't it?

Anyway as I was getting worried about the future, the time I could spend looking about these apps, I decided to move this blog to something in the :cloud:, easy to add content to (which the django app was not) and where people would enjoy read articles (so nice UX experience). So here's the v2, I hope you'll enjoy it! If anything's wrong or you dislike, PLEASE, let me know via [[https://twitter.com/juan__wolf/][twitter]] or opening an issue in [[https://github.com/juanwolf/blog/][github]].
